.class public Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/exceptions/CognitoLambdaValidationException;
.super Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/exceptions/CognitoIdentityProviderException;
.source "CognitoLambdaValidationException.java"
