.class public Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/exceptions/CognitoResourceNotFoundException;
.super Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/exceptions/CognitoIdentityProviderException;
.source "CognitoResourceNotFoundException.java"
