.class public Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/exceptions/CognitoCodeExpiredException;
.super Lcom/amazonaws/mobileconnectors/cognitoidentityprovider/exceptions/CognitoIdentityProviderException;
.source "CognitoCodeExpiredException.java"
