package com.bytedance.sdk.openadsdk.WcQ;

import android.content.Context;
import android.graphics.Color;
import android.graphics.drawable.Drawable;
import android.text.TextUtils;
import android.util.AttributeSet;
import android.view.View;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.SeekBar;
import com.bytedance.sdk.component.utils.cY;
import com.bytedance.sdk.openadsdk.utils.cdg;
import com.bytedance.sdk.openadsdk.utils.eZI;
/* loaded from: classes3.dex */
public class PiB extends com.bytedance.sdk.openadsdk.core.Pfn.cFZ {
    public PiB(Context context) {
        this(context, null);
    }

    private void oJ(Context context) {
        setId(520093726);
        setBackgroundColor(-1);
        com.bytedance.sdk.openadsdk.core.Pfn.cFZ cfz = new com.bytedance.sdk.openadsdk.core.Pfn.cFZ(context);
        cfz.setId(eZI.f13413oo);
        cfz.setLayoutParams(new RelativeLayout.LayoutParams(-1, -1));
        cfz.setBackgroundColor(0);
        cfz.setGravity(17);
        addView(cfz);
        View exVar = new com.bytedance.sdk.openadsdk.core.Pfn.ex(context);
        exVar.setId(eZI.f13416rg);
        exVar.setLayoutParams(new RelativeLayout.LayoutParams(-1, -1));
        cfz.addView(exVar);
        com.bytedance.sdk.openadsdk.core.Pfn.ba baVar = new com.bytedance.sdk.openadsdk.core.Pfn.ba(context);
        baVar.setId(eZI.ZMY);
        int ZYk = cdg.ZYk(context, 60.0f);
        RelativeLayout.LayoutParams layoutParams = new RelativeLayout.LayoutParams(ZYk, ZYk);
        layoutParams.addRule(13);
        baVar.setLayoutParams(layoutParams);
        baVar.setIndeterminateDrawable(com.bytedance.sdk.openadsdk.utils.dLZ.oJ(context, "tt_video_loading_progress_bar"));
        cfz.addView(baVar);
        com.bytedance.sdk.openadsdk.core.Pfn.Pfn pfn = new com.bytedance.sdk.openadsdk.core.Pfn.Pfn(context);
        pfn.setId(eZI.Zjw);
        RelativeLayout.LayoutParams layoutParams2 = new RelativeLayout.LayoutParams(-2, -2);
        layoutParams2.addRule(13);
        pfn.setLayoutParams(layoutParams2);
        pfn.setGravity(1);
        pfn.setOrientation(1);
        pfn.setVisibility(8);
        cfz.addView(pfn);
        com.bytedance.sdk.openadsdk.core.Pfn.ex exVar2 = new com.bytedance.sdk.openadsdk.core.Pfn.ex(context);
        exVar2.setId(eZI.XSu);
        exVar2.setLayoutParams(new LinearLayout.LayoutParams(-2, -2));
        exVar2.setImageDrawable(com.bytedance.sdk.openadsdk.utils.dLZ.oJ(context, "tt_refreshing_video_textpage"));
        ImageView.ScaleType scaleType = ImageView.ScaleType.CENTER;
        exVar2.setScaleType(scaleType);
        pfn.addView(exVar2);
        com.bytedance.sdk.openadsdk.core.Pfn.so soVar = new com.bytedance.sdk.openadsdk.core.Pfn.so(context);
        soVar.setId(eZI.Oof);
        soVar.setLayoutParams(new LinearLayout.LayoutParams(-2, -2));
        soVar.setText(cY.oJ(context, "tt_video_retry_des_txt"));
        soVar.setTextColor(Color.parseColor("#999999"));
        pfn.addView(soVar);
        com.bytedance.sdk.openadsdk.core.Pfn.ex exVar3 = new com.bytedance.sdk.openadsdk.core.Pfn.ex(context);
        exVar3.setId(eZI.NX);
        RelativeLayout.LayoutParams layoutParams3 = new RelativeLayout.LayoutParams(-2, -2);
        layoutParams3.addRule(13);
        exVar3.setLayoutParams(layoutParams3);
        exVar3.setScaleType(scaleType);
        exVar3.setImageDrawable(com.bytedance.sdk.openadsdk.utils.dLZ.oJ(context, "tt_play_movebar_textpage"));
        exVar3.setVisibility(8);
        addView(exVar3);
        com.bytedance.sdk.openadsdk.core.Pfn.ex exVar4 = new com.bytedance.sdk.openadsdk.core.Pfn.ex(context);
        exVar4.setId(eZI.yB);
        int ZYk2 = cdg.ZYk(context, 30.0f);
        RelativeLayout.LayoutParams layoutParams4 = new RelativeLayout.LayoutParams(ZYk2, ZYk2);
        layoutParams4.addRule(21);
        layoutParams4.addRule(11);
        int ZYk3 = cdg.ZYk(context, 7.0f);
        layoutParams4.setMarginEnd(ZYk3);
        layoutParams4.rightMargin = ZYk3;
        layoutParams4.topMargin = ZYk3;
        exVar4.setLayoutParams(layoutParams4);
        exVar4.setBackground(com.bytedance.sdk.openadsdk.utils.dLZ.oJ(context, "tt_detail_video_btn_bg"));
        exVar4.setScaleType(scaleType);
        exVar4.setImageDrawable(com.bytedance.sdk.openadsdk.utils.dLZ.oJ(context, "tt_close_move_detail"));
        addView(exVar4);
        com.bytedance.sdk.openadsdk.core.Pfn.so soVar2 = new com.bytedance.sdk.openadsdk.core.Pfn.so(context);
        soVar2.setId(eZI.f13420uq);
        RelativeLayout.LayoutParams layoutParams5 = new RelativeLayout.LayoutParams(-1, -2);
        layoutParams5.addRule(9);
        layoutParams5.addRule(20);
        layoutParams5.addRule(10);
        soVar2.setLayoutParams(layoutParams5);
        soVar2.setBackground(com.bytedance.sdk.openadsdk.utils.dLZ.oJ(context, "tt_video_black_desc_gradient"));
        TextUtils.TruncateAt truncateAt = TextUtils.TruncateAt.END;
        soVar2.setEllipsize(truncateAt);
        soVar2.setMaxLines(2);
        int ZYk4 = cdg.ZYk(context, 15.0f);
        soVar2.setPadding(ZYk4, cdg.ZYk(context, 14.0f), ZYk4, 0);
        soVar2.setSingleLine(false);
        soVar2.setTextColor(-1);
        soVar2.setTextSize(2, 17.0f);
        soVar2.setVisibility(8);
        addView(soVar2);
        com.bytedance.sdk.openadsdk.core.Pfn.cFZ cfz2 = new com.bytedance.sdk.openadsdk.core.Pfn.cFZ(context);
        cfz2.setId(eZI.uaj);
        RelativeLayout.LayoutParams layoutParams6 = new RelativeLayout.LayoutParams(-1, -2);
        layoutParams6.addRule(10);
        cfz2.setLayoutParams(layoutParams6);
        cfz2.setBackground(com.bytedance.sdk.openadsdk.utils.dLZ.oJ(context, "tt_video_black_desc_gradient"));
        cfz2.setGravity(16);
        cfz2.setVisibility(8);
        addView(cfz2);
        com.bytedance.sdk.openadsdk.core.Pfn.ex exVar5 = new com.bytedance.sdk.openadsdk.core.Pfn.ex(context);
        int i10 = eZI.LE;
        exVar5.setId(i10);
        RelativeLayout.LayoutParams layoutParams7 = new RelativeLayout.LayoutParams(-2, -1);
        layoutParams7.addRule(15);
        int ZYk5 = cdg.ZYk(context, 12.0f);
        layoutParams7.leftMargin = ZYk5;
        layoutParams7.setMarginStart(ZYk5);
        exVar5.setLayoutParams(layoutParams7);
        exVar5.setScaleType(scaleType);
        exVar5.setImageDrawable(com.bytedance.sdk.openadsdk.utils.dLZ.oJ(context, "tt_leftbackbutton_titlebar_photo_preview"));
        cfz2.addView(exVar5);
        com.bytedance.sdk.openadsdk.core.Pfn.so soVar3 = new com.bytedance.sdk.openadsdk.core.Pfn.so(context);
        soVar3.setId(eZI.WGj);
        RelativeLayout.LayoutParams layoutParams8 = new RelativeLayout.LayoutParams(-2, -1);
        layoutParams8.addRule(15);
        int ZYk6 = cdg.ZYk(context, 16.0f);
        layoutParams8.leftMargin = ZYk6;
        layoutParams8.rightMargin = ZYk;
        layoutParams8.setMarginStart(ZYk6);
        layoutParams8.setMarginEnd(ZYk);
        layoutParams8.addRule(17, i10);
        int i11 = eZI.UUI;
        layoutParams8.addRule(0, i11);
        layoutParams8.addRule(1, i10);
        layoutParams8.addRule(16, i11);
        soVar3.setLayoutParams(layoutParams8);
        soVar3.setEllipsize(truncateAt);
        soVar3.setGravity(16);
        soVar3.setMaxLines(1);
        soVar3.setSingleLine(true);
        soVar3.setTextColor(-1);
        soVar3.setTextSize(2, 17.0f);
        cfz2.addView(soVar3);
        com.bytedance.sdk.openadsdk.core.Pfn.Pfn pfn2 = new com.bytedance.sdk.openadsdk.core.Pfn.Pfn(context);
        pfn2.setId(i11);
        RelativeLayout.LayoutParams layoutParams9 = new RelativeLayout.LayoutParams(-2, -2);
        layoutParams9.addRule(21);
        layoutParams9.addRule(11);
        int ZYk7 = cdg.ZYk(context, 14.0f);
        layoutParams9.rightMargin = ZYk7;
        layoutParams9.setMarginEnd(ZYk7);
        pfn2.setLayoutParams(layoutParams9);
        pfn2.setGravity(16);
        pfn2.setOrientation(1);
        cfz2.addView(pfn2);
        com.bytedance.sdk.openadsdk.core.Pfn.so soVar4 = new com.bytedance.sdk.openadsdk.core.Pfn.so(context);
        soVar4.setId(eZI.Amz);
        LinearLayout.LayoutParams layoutParams10 = new LinearLayout.LayoutParams(-2, -2);
        layoutParams10.gravity = 1;
        soVar4.setLayoutParams(layoutParams10);
        soVar4.setGravity(16);
        soVar4.setMaxLines(1);
        soVar4.setSingleLine(true);
        soVar4.setTextColor(-1);
        soVar4.setTextSize(2, 12.0f);
        pfn2.addView(soVar4);
        com.bytedance.sdk.openadsdk.core.Pfn.Pfn pfn3 = new com.bytedance.sdk.openadsdk.core.Pfn.Pfn(context);
        pfn3.setId(eZI.ypD);
        RelativeLayout.LayoutParams layoutParams11 = new RelativeLayout.LayoutParams(-2, cdg.ZYk(context, 40.0f));
        layoutParams11.addRule(12);
        layoutParams11.addRule(21);
        layoutParams11.addRule(11);
        pfn3.setLayoutParams(layoutParams11);
        pfn3.setGravity(16);
        pfn3.setOrientation(0);
        pfn3.setVisibility(8);
        addView(pfn3);
        com.bytedance.sdk.openadsdk.core.Pfn.so soVar5 = new com.bytedance.sdk.openadsdk.core.Pfn.so(context);
        soVar5.setId(eZI.SB);
        LinearLayout.LayoutParams layoutParams12 = new LinearLayout.LayoutParams(-2, -2);
        layoutParams12.leftMargin = ZYk6;
        layoutParams12.rightMargin = ZYk5;
        layoutParams12.setMarginEnd(ZYk5);
        layoutParams12.setMarginStart(ZYk6);
        soVar5.setLayoutParams(layoutParams12);
        soVar5.setText(cY.oJ(context, "tt_00_00"));
        soVar5.setTextColor(-1);
        soVar5.setTextSize(2, 10.0f);
        pfn3.addView(soVar5);
        SeekBar seekBar = new SeekBar(context);
        seekBar.setId(eZI.edj);
        LinearLayout.LayoutParams layoutParams13 = new LinearLayout.LayoutParams(0, cdg.ZYk(context, 5.0f));
        layoutParams13.gravity = 16;
        seekBar.setLayoutParams(layoutParams13);
        seekBar.setMax(100);
        seekBar.setPadding(0, 0, 0, 0);
        seekBar.setProgressDrawable(com.bytedance.sdk.openadsdk.utils.dLZ.oJ(context, "tt_seek_progress"));
        seekBar.setThumb(com.bytedance.sdk.openadsdk.utils.dLZ.oJ(context, "tt_seek_thumb"));
        seekBar.setThumbOffset(0);
        pfn3.addView(seekBar);
        com.bytedance.sdk.openadsdk.core.Pfn.so soVar6 = new com.bytedance.sdk.openadsdk.core.Pfn.so(context);
        soVar6.setId(eZI.eW);
        LinearLayout.LayoutParams layoutParams14 = new LinearLayout.LayoutParams(-2, -2);
        layoutParams14.leftMargin = ZYk5;
        layoutParams14.rightMargin = ZYk6;
        layoutParams14.setMarginEnd(ZYk6);
        layoutParams14.setMarginStart(ZYk5);
        soVar6.setLayoutParams(layoutParams14);
        soVar6.setText(cY.oJ(context, "tt_00_00"));
        soVar6.setTextColor(-1);
        soVar6.setTextSize(2, 10.0f);
        pfn3.addView(soVar6);
        com.bytedance.sdk.openadsdk.core.Pfn.ex exVar6 = new com.bytedance.sdk.openadsdk.core.Pfn.ex(context);
        exVar6.setId(eZI.dZS);
        exVar6.setLayoutParams(new LinearLayout.LayoutParams(-2, -1));
        exVar6.setPadding(ZYk6, 0, ZYk6, 0);
        exVar6.setScaleType(scaleType);
        exVar6.setVisibility(8);
        exVar6.setImageDrawable(cY.tB(context, "tt_enlarge_video"));
        pfn3.addView(exVar6);
        View btz = new BTZ(context);
        btz.setId(eZI.MVA);
        btz.setLayoutParams(new RelativeLayout.LayoutParams(-1, -1));
        addView(btz);
        com.bytedance.sdk.openadsdk.core.Pfn.so soVar7 = new com.bytedance.sdk.openadsdk.core.Pfn.so(context);
        soVar7.setId(eZI.Wd);
        RelativeLayout.LayoutParams layoutParams15 = new RelativeLayout.LayoutParams(-2, -2);
        layoutParams15.leftMargin = ZYk5;
        layoutParams15.addRule(9);
        layoutParams15.addRule(20);
        soVar7.setLayoutParams(layoutParams15);
        soVar7.setBackgroundColor(Color.parseColor("#00000000"));
        soVar7.setText("close");
        soVar7.setMinHeight(cdg.ZYk(context, 44.0f));
        soVar7.setCompoundDrawablesWithIntrinsicBounds(com.bytedance.sdk.openadsdk.utils.dLZ.oJ(context, "tt_shadow_btn_back"), (Drawable) null, (Drawable) null, (Drawable) null);
        addView(soVar7);
    }

    public PiB(Context context, AttributeSet attributeSet) {
        this(context, attributeSet, 0);
    }

    public PiB(Context context, AttributeSet attributeSet, int i10) {
        super(context, attributeSet, i10);
        oJ(context);
    }
}
