package com.bytedance.sdk.openadsdk.component.reward.view;

import android.content.Context;
import android.graphics.Color;
import android.view.View;
import android.widget.FrameLayout;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import androidx.core.view.ViewCompat;
import com.bytedance.sdk.openadsdk.core.model.cY;
import com.bytedance.sdk.openadsdk.core.widget.PAGLogoView;
import com.bytedance.sdk.openadsdk.core.widget.si;
import com.bytedance.sdk.openadsdk.utils.cdg;
import com.bytedance.sdk.openadsdk.utils.eZI;
/* loaded from: classes3.dex */
public class ba {
    public static void oJ(FrameLayout frameLayout, cY cYVar) {
        Context context = frameLayout.getContext();
        com.bytedance.sdk.openadsdk.core.Pfn.cFZ cfz = new com.bytedance.sdk.openadsdk.core.Pfn.cFZ(context);
        cfz.setId(eZI.f13409jr);
        cfz.setBackgroundColor(Color.parseColor("#F8F8F8"));
        frameLayout.addView(cfz, new FrameLayout.LayoutParams(-1, -1));
        View btz = new com.bytedance.sdk.openadsdk.common.BTZ(context);
        btz.setId(eZI.Xe);
        cfz.addView(btz, new RelativeLayout.LayoutParams(-1, -1));
        com.bytedance.sdk.openadsdk.core.Pfn.Pfn pfn = new com.bytedance.sdk.openadsdk.core.Pfn.Pfn(context);
        pfn.setId(eZI.f13419tb);
        pfn.setOrientation(1);
        pfn.setVisibility(8);
        pfn.setGravity(1);
        pfn.setId(eZI.XAo);
        RelativeLayout.LayoutParams layoutParams = new RelativeLayout.LayoutParams(-1, -2);
        layoutParams.addRule(13);
        cfz.addView(pfn, layoutParams);
        si siVar = new si(context);
        siVar.setId(eZI.IUZ);
        pfn.addView(siVar, new LinearLayout.LayoutParams(cdg.ZYk(context, 80.0f), cdg.ZYk(context, 80.0f)));
        com.bytedance.sdk.openadsdk.core.Pfn.so soVar = new com.bytedance.sdk.openadsdk.core.Pfn.so(context);
        soVar.setId(eZI.Ln);
        soVar.setTextColor(Color.parseColor("#161823"));
        soVar.setTextSize(2, 24.0f);
        LinearLayout.LayoutParams layoutParams2 = new LinearLayout.LayoutParams(-2, -2);
        layoutParams2.topMargin = cdg.ZYk(context, 12.0f);
        pfn.addView(soVar, layoutParams2);
        com.bytedance.sdk.openadsdk.core.Pfn.so soVar2 = new com.bytedance.sdk.openadsdk.core.Pfn.so(context);
        soVar2.setId(eZI.LpP);
        soVar2.setGravity(17);
        soVar2.setTextColor(Color.parseColor("#80161823"));
        soVar2.setTextSize(2, 16.0f);
        soVar2.setTextAlignment(4);
        LinearLayout.LayoutParams layoutParams3 = new LinearLayout.LayoutParams(-2, -2);
        int ZYk = cdg.ZYk(context, 60.0f);
        layoutParams3.leftMargin = ZYk;
        layoutParams3.rightMargin = ZYk;
        layoutParams3.setMarginStart(ZYk);
        layoutParams3.setMarginEnd(layoutParams3.rightMargin);
        layoutParams3.topMargin = cdg.ZYk(context, 8.0f);
        pfn.addView(soVar2, layoutParams3);
        com.bytedance.sdk.openadsdk.core.Pfn.so soVar3 = new com.bytedance.sdk.openadsdk.core.Pfn.so(context);
        soVar3.setId(eZI.nke);
        soVar3.setGravity(17);
        soVar3.setTextColor(-1);
        soVar3.setText(com.bytedance.sdk.component.utils.cY.oJ(context, "tt_video_mobile_go_detail"));
        soVar3.setBackground(com.bytedance.sdk.openadsdk.utils.dLZ.oJ(context, "tt_reward_video_download_btn_bg"));
        LinearLayout.LayoutParams layoutParams4 = new LinearLayout.LayoutParams(cdg.ZYk(context, 255.0f), cdg.ZYk(context, 44.0f));
        layoutParams4.topMargin = cdg.ZYk(context, 32.0f);
        pfn.addView(soVar3, layoutParams4);
        com.bytedance.sdk.openadsdk.core.Pfn.so soVar4 = new com.bytedance.sdk.openadsdk.core.Pfn.so(context);
        soVar4.setId(eZI.HL);
        soVar4.setGravity(17);
        soVar4.setTextColor(ViewCompat.MEASURED_STATE_MASK);
        soVar4.setText("Sorry,this AD fails to load...");
        soVar4.setVisibility(8);
        soVar4.setGravity(1);
        RelativeLayout.LayoutParams layoutParams5 = new RelativeLayout.LayoutParams(-1, -2);
        layoutParams5.addRule(13);
        cfz.addView(soVar4, layoutParams5);
        View createPAGLogoViewByMaterial = PAGLogoView.createPAGLogoViewByMaterial(context, cYVar);
        createPAGLogoViewByMaterial.setId(eZI.Jc);
        RelativeLayout.LayoutParams layoutParams6 = new RelativeLayout.LayoutParams(-2, cdg.ZYk(context, 14.0f));
        layoutParams6.addRule(12);
        int ZYk2 = cdg.ZYk(context, 16.0f);
        layoutParams6.leftMargin = ZYk2;
        layoutParams6.setMarginStart(ZYk2);
        layoutParams6.bottomMargin = cdg.ZYk(context, 20.0f);
        cfz.addView(createPAGLogoViewByMaterial, layoutParams6);
    }

    public static void oJ(FrameLayout frameLayout) {
        Context context = frameLayout.getContext();
        View pfn = new Pfn(context);
        pfn.setId(eZI.BTZ);
        pfn.setVisibility(8);
        FrameLayout.LayoutParams layoutParams = new FrameLayout.LayoutParams(-1, -2);
        layoutParams.gravity = 80;
        frameLayout.addView(pfn, layoutParams);
        View pfn2 = new com.bytedance.sdk.openadsdk.core.Pfn.Pfn(context);
        pfn2.setId(eZI.PiB);
        pfn2.setVisibility(8);
        frameLayout.addView(pfn2, new FrameLayout.LayoutParams(-1, -1));
        View baVar = new com.bytedance.sdk.component.jFA.ba(context, true);
        baVar.setLayerType(2, null);
        baVar.setVisibility(4);
        baVar.setId(eZI.WcQ);
        frameLayout.addView(baVar, new FrameLayout.LayoutParams(-1, -1));
        View frameLayout2 = new FrameLayout(context);
        frameLayout2.setId(eZI.awB);
        frameLayout2.setVisibility(4);
        frameLayout.addView(frameLayout2, new FrameLayout.LayoutParams(-1, -1));
        View baVar2 = new com.bytedance.sdk.component.jFA.ba(context, true);
        baVar2.setVisibility(8);
        baVar2.setId(eZI.eZI);
        frameLayout.addView(baVar2, new FrameLayout.LayoutParams(-1, -1));
        frameLayout.addView(new RFEndCardBackUpLayout(context), new FrameLayout.LayoutParams(-1, -1));
    }
}
