package com.vungle.ads.internal.model;

import com.mbridge.msdk.foundation.entity.CampaignEx;
import com.ss.ttvideoengine.selector.strategy.GearStrategy;
import com.vungle.ads.internal.Constants;
import com.vungle.ads.internal.model.AdPayload;
import java.util.List;
import java.util.Map;
import kotlin.Metadata;
import kotlin.Unit;
import kotlin.jvm.internal.Intrinsics;
import kotlinx.serialization.KSerializer;
import kotlinx.serialization.UnknownFieldException;
import kotlinx.serialization.descriptors.SerialDescriptor;
import kotlinx.serialization.encoding.Decoder;
import kotlinx.serialization.encoding.Encoder;
import kotlinx.serialization.encoding.d;
import ms.c;
import org.jetbrains.annotations.NotNull;
import tt.a;
import vt.f;
import vt.h2;
import vt.i;
import vt.m0;
import vt.r2;
import vt.v0;
import vt.w2;
/* compiled from: AdPayload.kt */
@c
@Metadata
/* loaded from: classes7.dex */
public final class AdPayload$AdUnit$$serializer implements m0<AdPayload.AdUnit> {
    @NotNull
    public static final AdPayload$AdUnit$$serializer INSTANCE;
    public static final /* synthetic */ SerialDescriptor descriptor;

    static {
        AdPayload$AdUnit$$serializer adPayload$AdUnit$$serializer = new AdPayload$AdUnit$$serializer();
        INSTANCE = adPayload$AdUnit$$serializer;
        h2 h2Var = new h2("com.vungle.ads.internal.model.AdPayload.AdUnit", adPayload$AdUnit$$serializer, 29);
        h2Var.o("id", true);
        h2Var.o("ad_type", true);
        h2Var.o("ad_source", true);
        h2Var.o("expiry", true);
        h2Var.o("deeplink_url", true);
        h2Var.o("click_coordinates_enabled", true);
        h2Var.o("ad_load_optimization", true);
        h2Var.o("template_heartbeat_check", true);
        h2Var.o("mediation_name", true);
        h2Var.o("info", true);
        h2Var.o("sleep", true);
        h2Var.o(GearStrategy.GEAR_STRATEGY_KEY_ERROR_CODE, true);
        h2Var.o("tpat", true);
        h2Var.o("vm_url", true);
        h2Var.o("vm_version", true);
        h2Var.o("ad_market_id", true);
        h2Var.o("notification", true);
        h2Var.o(Constants.LOAD_AD, true);
        h2Var.o("viewability", true);
        h2Var.o("template_url", true);
        h2Var.o("template_type", true);
        h2Var.o("template_settings", true);
        h2Var.o(CampaignEx.JSON_KEY_CREATIVE_ID, true);
        h2Var.o("app_id", true);
        h2Var.o("show_close", true);
        h2Var.o("show_close_incentivized", true);
        h2Var.o("ad_size", true);
        h2Var.o("cacheable_assets_required", true);
        h2Var.o("webview_settings", true);
        descriptor = h2Var;
    }

    private AdPayload$AdUnit$$serializer() {
    }

    @Override // vt.m0
    @NotNull
    public KSerializer<?>[] childSerializers() {
        w2 w2Var = w2.f69539a;
        KSerializer<?> t10 = a.t(w2Var);
        KSerializer<?> t11 = a.t(w2Var);
        KSerializer<?> t12 = a.t(w2Var);
        v0 v0Var = v0.f69529a;
        KSerializer<?> t13 = a.t(v0Var);
        KSerializer<?> t14 = a.t(w2Var);
        i iVar = i.f69441a;
        return new KSerializer[]{t10, t11, t12, t13, t14, a.t(iVar), a.t(iVar), a.t(iVar), a.t(w2Var), a.t(w2Var), a.t(v0Var), a.t(v0Var), a.t(AdPayload.TpatSerializer.INSTANCE), a.t(w2Var), a.t(w2Var), a.t(w2Var), a.t(new f(w2Var)), a.t(new f(w2Var)), a.t(AdPayload$ViewAbility$$serializer.INSTANCE), a.t(w2Var), a.t(w2Var), a.t(AdPayload$TemplateSettings$$serializer.INSTANCE), a.t(w2Var), a.t(w2Var), a.t(v0Var), a.t(v0Var), a.t(AdPayload$AdSizeInfo$$serializer.INSTANCE), a.t(iVar), a.t(AdPayload$WebViewSettings$$serializer.INSTANCE)};
    }

    @Override // st.c
    @NotNull
    public AdPayload.AdUnit deserialize(@NotNull Decoder decoder) {
        Integer num;
        String str;
        List list;
        String str2;
        AdPayload.TemplateSettings templateSettings;
        Boolean bool;
        int i10;
        String str3;
        Integer num2;
        Object obj;
        String str4;
        Object obj2;
        Object obj3;
        Object obj4;
        Object obj5;
        String str5;
        AdPayload.WebViewSettings webViewSettings;
        AdPayload.AdSizeInfo adSizeInfo;
        Integer num3;
        String str6;
        String str7;
        String str8;
        AdPayload.ViewAbility viewAbility;
        List list2;
        String str9;
        String str10;
        Object obj6;
        Object obj7;
        Map map;
        Object obj8;
        Object obj9;
        Object obj10;
        AdPayload.WebViewSettings webViewSettings2;
        String str11;
        Map map2;
        String str12;
        String str13;
        String str14;
        List list3;
        List list4;
        AdPayload.ViewAbility viewAbility2;
        String str15;
        Object obj11;
        AdPayload.TemplateSettings templateSettings2;
        String str16;
        String str17;
        Object obj12;
        Integer num4;
        AdPayload.AdSizeInfo adSizeInfo2;
        Boolean bool2;
        Map map3;
        List list5;
        Boolean bool3;
        AdPayload.TemplateSettings templateSettings3;
        String str18;
        Map map4;
        List list6;
        String str19;
        Map map5;
        List list7;
        String str20;
        String str21;
        Intrinsics.checkNotNullParameter(decoder, "decoder");
        SerialDescriptor descriptor2 = getDescriptor();
        kotlinx.serialization.encoding.c beginStructure = decoder.beginStructure(descriptor2);
        if (beginStructure.decodeSequentially()) {
            w2 w2Var = w2.f69539a;
            Object decodeNullableSerializableElement = beginStructure.decodeNullableSerializableElement(descriptor2, 0, w2Var, null);
            Object decodeNullableSerializableElement2 = beginStructure.decodeNullableSerializableElement(descriptor2, 1, w2Var, null);
            obj6 = beginStructure.decodeNullableSerializableElement(descriptor2, 2, w2Var, null);
            v0 v0Var = v0.f69529a;
            obj7 = beginStructure.decodeNullableSerializableElement(descriptor2, 3, v0Var, null);
            obj5 = beginStructure.decodeNullableSerializableElement(descriptor2, 4, w2Var, null);
            i iVar = i.f69441a;
            obj3 = beginStructure.decodeNullableSerializableElement(descriptor2, 5, iVar, null);
            obj4 = beginStructure.decodeNullableSerializableElement(descriptor2, 6, iVar, null);
            obj2 = beginStructure.decodeNullableSerializableElement(descriptor2, 7, iVar, null);
            Object decodeNullableSerializableElement3 = beginStructure.decodeNullableSerializableElement(descriptor2, 8, w2Var, null);
            obj = beginStructure.decodeNullableSerializableElement(descriptor2, 9, w2Var, null);
            Object decodeNullableSerializableElement4 = beginStructure.decodeNullableSerializableElement(descriptor2, 10, v0Var, null);
            num2 = beginStructure.decodeNullableSerializableElement(descriptor2, 11, v0Var, null);
            str3 = decodeNullableSerializableElement;
            Object decodeNullableSerializableElement5 = beginStructure.decodeNullableSerializableElement(descriptor2, 12, AdPayload.TpatSerializer.INSTANCE, null);
            Object decodeNullableSerializableElement6 = beginStructure.decodeNullableSerializableElement(descriptor2, 13, w2Var, null);
            map = decodeNullableSerializableElement5;
            str10 = beginStructure.decodeNullableSerializableElement(descriptor2, 14, w2Var, null);
            str9 = beginStructure.decodeNullableSerializableElement(descriptor2, 15, w2Var, null);
            str = decodeNullableSerializableElement6;
            list2 = beginStructure.decodeNullableSerializableElement(descriptor2, 16, new f(w2Var), null);
            Object decodeNullableSerializableElement7 = beginStructure.decodeNullableSerializableElement(descriptor2, 17, new f(w2Var), null);
            Object decodeNullableSerializableElement8 = beginStructure.decodeNullableSerializableElement(descriptor2, 18, AdPayload$ViewAbility$$serializer.INSTANCE, null);
            Object decodeNullableSerializableElement9 = beginStructure.decodeNullableSerializableElement(descriptor2, 19, w2Var, null);
            viewAbility = decodeNullableSerializableElement8;
            Object decodeNullableSerializableElement10 = beginStructure.decodeNullableSerializableElement(descriptor2, 20, w2Var, null);
            str2 = decodeNullableSerializableElement9;
            Object decodeNullableSerializableElement11 = beginStructure.decodeNullableSerializableElement(descriptor2, 21, AdPayload$TemplateSettings$$serializer.INSTANCE, null);
            Object decodeNullableSerializableElement12 = beginStructure.decodeNullableSerializableElement(descriptor2, 22, w2Var, null);
            Object decodeNullableSerializableElement13 = beginStructure.decodeNullableSerializableElement(descriptor2, 23, w2Var, null);
            obj8 = beginStructure.decodeNullableSerializableElement(descriptor2, 24, v0Var, null);
            str6 = decodeNullableSerializableElement13;
            num3 = beginStructure.decodeNullableSerializableElement(descriptor2, 25, v0Var, null);
            Object decodeNullableSerializableElement14 = beginStructure.decodeNullableSerializableElement(descriptor2, 26, AdPayload$AdSizeInfo$$serializer.INSTANCE, null);
            str7 = decodeNullableSerializableElement12;
            i10 = 536870911;
            bool = beginStructure.decodeNullableSerializableElement(descriptor2, 27, iVar, null);
            str4 = decodeNullableSerializableElement3;
            templateSettings = decodeNullableSerializableElement11;
            list = decodeNullableSerializableElement7;
            num = decodeNullableSerializableElement4;
            adSizeInfo = decodeNullableSerializableElement14;
            webViewSettings = beginStructure.decodeNullableSerializableElement(descriptor2, 28, AdPayload$WebViewSettings$$serializer.INSTANCE, null);
            str5 = decodeNullableSerializableElement2;
            str8 = decodeNullableSerializableElement10;
        } else {
            boolean z10 = true;
            Object obj13 = null;
            AdPayload.WebViewSettings webViewSettings3 = null;
            Integer num5 = null;
            Object obj14 = null;
            String str22 = null;
            String str23 = null;
            Object obj15 = null;
            Object obj16 = null;
            Object obj17 = null;
            num = null;
            Object obj18 = null;
            Map map6 = null;
            String str24 = null;
            String str25 = null;
            String str26 = null;
            List list8 = null;
            List list9 = null;
            AdPayload.ViewAbility viewAbility3 = null;
            String str27 = null;
            String str28 = null;
            AdPayload.TemplateSettings templateSettings4 = null;
            String str29 = null;
            String str30 = null;
            Object obj19 = null;
            Integer num6 = null;
            AdPayload.AdSizeInfo adSizeInfo3 = null;
            Boolean bool4 = null;
            String str31 = null;
            int i11 = 0;
            Object obj20 = null;
            while (z10) {
                int decodeElementIndex = beginStructure.decodeElementIndex(descriptor2);
                switch (decodeElementIndex) {
                    case -1:
                        obj9 = obj13;
                        obj10 = obj20;
                        webViewSettings2 = webViewSettings3;
                        str11 = str23;
                        map2 = map6;
                        str12 = str24;
                        str13 = str25;
                        str14 = str26;
                        list3 = list8;
                        list4 = list9;
                        viewAbility2 = viewAbility3;
                        str15 = str27;
                        obj11 = str28;
                        templateSettings2 = templateSettings4;
                        str16 = str29;
                        str17 = str30;
                        obj12 = obj19;
                        num4 = num6;
                        adSizeInfo2 = adSizeInfo3;
                        bool2 = bool4;
                        Unit unit = Unit.f60915a;
                        z10 = false;
                        map3 = map2;
                        str23 = str11;
                        obj20 = obj10;
                        list5 = list4;
                        list8 = list3;
                        Object obj21 = obj11;
                        bool3 = bool2;
                        templateSettings3 = templateSettings2;
                        str28 = obj21;
                        break;
                    case 0:
                        obj9 = obj13;
                        obj10 = obj20;
                        webViewSettings2 = webViewSettings3;
                        String str32 = str23;
                        map2 = map6;
                        str12 = str24;
                        str13 = str25;
                        str14 = str26;
                        list3 = list8;
                        list4 = list9;
                        viewAbility2 = viewAbility3;
                        str15 = str27;
                        obj11 = str28;
                        templateSettings2 = templateSettings4;
                        str16 = str29;
                        str17 = str30;
                        obj12 = obj19;
                        num4 = num6;
                        adSizeInfo2 = adSizeInfo3;
                        bool2 = bool4;
                        str11 = str32;
                        Object decodeNullableSerializableElement15 = beginStructure.decodeNullableSerializableElement(descriptor2, 0, w2.f69539a, str31);
                        i11 |= 1;
                        Unit unit2 = Unit.f60915a;
                        str31 = decodeNullableSerializableElement15;
                        map3 = map2;
                        str23 = str11;
                        obj20 = obj10;
                        list5 = list4;
                        list8 = list3;
                        Object obj212 = obj11;
                        bool3 = bool2;
                        templateSettings3 = templateSettings2;
                        str28 = obj212;
                        break;
                    case 1:
                        webViewSettings2 = webViewSettings3;
                        str12 = str24;
                        str13 = str25;
                        str14 = str26;
                        viewAbility2 = viewAbility3;
                        str15 = str27;
                        str16 = str29;
                        str17 = str30;
                        obj12 = obj19;
                        num4 = num6;
                        adSizeInfo2 = adSizeInfo3;
                        obj9 = obj13;
                        Object obj22 = obj20;
                        Object decodeNullableSerializableElement16 = beginStructure.decodeNullableSerializableElement(descriptor2, 1, w2.f69539a, str23);
                        i11 |= 2;
                        Unit unit3 = Unit.f60915a;
                        obj20 = obj22;
                        list5 = list9;
                        list8 = list8;
                        str23 = decodeNullableSerializableElement16;
                        map3 = map6;
                        bool3 = bool4;
                        templateSettings3 = templateSettings4;
                        str28 = str28;
                        break;
                    case 2:
                        webViewSettings2 = webViewSettings3;
                        str18 = str23;
                        map4 = map6;
                        str12 = str24;
                        str13 = str25;
                        str14 = str26;
                        list3 = list8;
                        list6 = list9;
                        viewAbility2 = viewAbility3;
                        str15 = str27;
                        obj11 = str28;
                        templateSettings2 = templateSettings4;
                        str16 = str29;
                        str17 = str30;
                        obj12 = obj19;
                        num4 = num6;
                        adSizeInfo2 = adSizeInfo3;
                        bool2 = bool4;
                        Object decodeNullableSerializableElement17 = beginStructure.decodeNullableSerializableElement(descriptor2, 2, w2.f69539a, obj20);
                        i11 |= 4;
                        Unit unit4 = Unit.f60915a;
                        obj9 = obj13;
                        obj20 = decodeNullableSerializableElement17;
                        map3 = map4;
                        list5 = list6;
                        str23 = str18;
                        list8 = list3;
                        Object obj2122 = obj11;
                        bool3 = bool2;
                        templateSettings3 = templateSettings2;
                        str28 = obj2122;
                        break;
                    case 3:
                        webViewSettings2 = webViewSettings3;
                        str12 = str24;
                        str13 = str25;
                        str14 = str26;
                        list3 = list8;
                        viewAbility2 = viewAbility3;
                        str15 = str27;
                        obj11 = str28;
                        templateSettings2 = templateSettings4;
                        str16 = str29;
                        str17 = str30;
                        obj12 = obj19;
                        num4 = num6;
                        adSizeInfo2 = adSizeInfo3;
                        bool2 = bool4;
                        Object decodeNullableSerializableElement18 = beginStructure.decodeNullableSerializableElement(descriptor2, 3, v0.f69529a, obj13);
                        i11 |= 8;
                        Unit unit5 = Unit.f60915a;
                        obj9 = decodeNullableSerializableElement18;
                        map3 = map6;
                        list5 = list9;
                        str23 = str23;
                        list8 = list3;
                        Object obj21222 = obj11;
                        bool3 = bool2;
                        templateSettings3 = templateSettings2;
                        str28 = obj21222;
                        break;
                    case 4:
                        webViewSettings2 = webViewSettings3;
                        str18 = str23;
                        map4 = map6;
                        str12 = str24;
                        str13 = str25;
                        str14 = str26;
                        list3 = list8;
                        list6 = list9;
                        viewAbility2 = viewAbility3;
                        str15 = str27;
                        obj11 = str28;
                        templateSettings2 = templateSettings4;
                        str16 = str29;
                        str17 = str30;
                        obj12 = obj19;
                        num4 = num6;
                        adSizeInfo2 = adSizeInfo3;
                        bool2 = bool4;
                        Object decodeNullableSerializableElement19 = beginStructure.decodeNullableSerializableElement(descriptor2, 4, w2.f69539a, obj18);
                        i11 |= 16;
                        Unit unit6 = Unit.f60915a;
                        obj9 = obj13;
                        obj18 = decodeNullableSerializableElement19;
                        map3 = map4;
                        list5 = list6;
                        str23 = str18;
                        list8 = list3;
                        Object obj212222 = obj11;
                        bool3 = bool2;
                        templateSettings3 = templateSettings2;
                        str28 = obj212222;
                        break;
                    case 5:
                        webViewSettings2 = webViewSettings3;
                        str19 = str23;
                        map5 = map6;
                        str12 = str24;
                        str13 = str25;
                        str14 = str26;
                        list3 = list8;
                        list7 = list9;
                        viewAbility2 = viewAbility3;
                        str15 = str27;
                        obj11 = str28;
                        templateSettings2 = templateSettings4;
                        str16 = str29;
                        str17 = str30;
                        obj12 = obj19;
                        num4 = num6;
                        adSizeInfo2 = adSizeInfo3;
                        bool2 = bool4;
                        Object decodeNullableSerializableElement20 = beginStructure.decodeNullableSerializableElement(descriptor2, 5, i.f69441a, obj16);
                        i11 |= 32;
                        Unit unit7 = Unit.f60915a;
                        obj9 = obj13;
                        obj16 = decodeNullableSerializableElement20;
                        map3 = map5;
                        list5 = list7;
                        str23 = str19;
                        list8 = list3;
                        Object obj2122222 = obj11;
                        bool3 = bool2;
                        templateSettings3 = templateSettings2;
                        str28 = obj2122222;
                        break;
                    case 6:
                        webViewSettings2 = webViewSettings3;
                        str19 = str23;
                        map5 = map6;
                        str12 = str24;
                        str13 = str25;
                        str14 = str26;
                        list3 = list8;
                        list7 = list9;
                        viewAbility2 = viewAbility3;
                        str15 = str27;
                        obj11 = str28;
                        templateSettings2 = templateSettings4;
                        str16 = str29;
                        str17 = str30;
                        obj12 = obj19;
                        num4 = num6;
                        adSizeInfo2 = adSizeInfo3;
                        bool2 = bool4;
                        Object decodeNullableSerializableElement21 = beginStructure.decodeNullableSerializableElement(descriptor2, 6, i.f69441a, obj17);
                        i11 |= 64;
                        Unit unit8 = Unit.f60915a;
                        obj9 = obj13;
                        obj17 = decodeNullableSerializableElement21;
                        map3 = map5;
                        list5 = list7;
                        str23 = str19;
                        list8 = list3;
                        Object obj21222222 = obj11;
                        bool3 = bool2;
                        templateSettings3 = templateSettings2;
                        str28 = obj21222222;
                        break;
                    case 7:
                        webViewSettings2 = webViewSettings3;
                        str19 = str23;
                        map5 = map6;
                        str12 = str24;
                        str13 = str25;
                        str14 = str26;
                        list3 = list8;
                        list7 = list9;
                        viewAbility2 = viewAbility3;
                        str15 = str27;
                        obj11 = str28;
                        templateSettings2 = templateSettings4;
                        str16 = str29;
                        str17 = str30;
                        obj12 = obj19;
                        num4 = num6;
                        adSizeInfo2 = adSizeInfo3;
                        bool2 = bool4;
                        Object decodeNullableSerializableElement22 = beginStructure.decodeNullableSerializableElement(descriptor2, 7, i.f69441a, obj15);
                        i11 |= 128;
                        Unit unit9 = Unit.f60915a;
                        obj9 = obj13;
                        obj15 = decodeNullableSerializableElement22;
                        map3 = map5;
                        list5 = list7;
                        str23 = str19;
                        list8 = list3;
                        Object obj212222222 = obj11;
                        bool3 = bool2;
                        templateSettings3 = templateSettings2;
                        str28 = obj212222222;
                        break;
                    case 8:
                        webViewSettings2 = webViewSettings3;
                        str19 = str23;
                        map5 = map6;
                        str12 = str24;
                        str13 = str25;
                        str14 = str26;
                        list3 = list8;
                        list7 = list9;
                        viewAbility2 = viewAbility3;
                        str15 = str27;
                        obj11 = str28;
                        templateSettings2 = templateSettings4;
                        str16 = str29;
                        str17 = str30;
                        obj12 = obj19;
                        num4 = num6;
                        adSizeInfo2 = adSizeInfo3;
                        bool2 = bool4;
                        Object decodeNullableSerializableElement23 = beginStructure.decodeNullableSerializableElement(descriptor2, 8, w2.f69539a, str22);
                        i11 |= 256;
                        Unit unit10 = Unit.f60915a;
                        obj9 = obj13;
                        str22 = decodeNullableSerializableElement23;
                        map3 = map5;
                        list5 = list7;
                        str23 = str19;
                        list8 = list3;
                        Object obj2122222222 = obj11;
                        bool3 = bool2;
                        templateSettings3 = templateSettings2;
                        str28 = obj2122222222;
                        break;
                    case 9:
                        webViewSettings2 = webViewSettings3;
                        str19 = str23;
                        map5 = map6;
                        str12 = str24;
                        str13 = str25;
                        str14 = str26;
                        list3 = list8;
                        list7 = list9;
                        viewAbility2 = viewAbility3;
                        str15 = str27;
                        obj11 = str28;
                        templateSettings2 = templateSettings4;
                        str16 = str29;
                        str17 = str30;
                        obj12 = obj19;
                        num4 = num6;
                        adSizeInfo2 = adSizeInfo3;
                        bool2 = bool4;
                        Object decodeNullableSerializableElement24 = beginStructure.decodeNullableSerializableElement(descriptor2, 9, w2.f69539a, obj14);
                        i11 |= 512;
                        Unit unit11 = Unit.f60915a;
                        obj9 = obj13;
                        obj14 = decodeNullableSerializableElement24;
                        map3 = map5;
                        list5 = list7;
                        str23 = str19;
                        list8 = list3;
                        Object obj21222222222 = obj11;
                        bool3 = bool2;
                        templateSettings3 = templateSettings2;
                        str28 = obj21222222222;
                        break;
                    case 10:
                        webViewSettings2 = webViewSettings3;
                        str19 = str23;
                        map5 = map6;
                        str12 = str24;
                        str13 = str25;
                        str14 = str26;
                        list3 = list8;
                        list7 = list9;
                        viewAbility2 = viewAbility3;
                        str15 = str27;
                        obj11 = str28;
                        templateSettings2 = templateSettings4;
                        str16 = str29;
                        str17 = str30;
                        obj12 = obj19;
                        num4 = num6;
                        adSizeInfo2 = adSizeInfo3;
                        bool2 = bool4;
                        Object decodeNullableSerializableElement25 = beginStructure.decodeNullableSerializableElement(descriptor2, 10, v0.f69529a, num);
                        i11 |= 1024;
                        Unit unit12 = Unit.f60915a;
                        obj9 = obj13;
                        num = decodeNullableSerializableElement25;
                        map3 = map5;
                        list5 = list7;
                        str23 = str19;
                        list8 = list3;
                        Object obj212222222222 = obj11;
                        bool3 = bool2;
                        templateSettings3 = templateSettings2;
                        str28 = obj212222222222;
                        break;
                    case 11:
                        webViewSettings2 = webViewSettings3;
                        str19 = str23;
                        map5 = map6;
                        str12 = str24;
                        str13 = str25;
                        str14 = str26;
                        list3 = list8;
                        list7 = list9;
                        viewAbility2 = viewAbility3;
                        str15 = str27;
                        obj11 = str28;
                        templateSettings2 = templateSettings4;
                        str16 = str29;
                        str17 = str30;
                        obj12 = obj19;
                        num4 = num6;
                        adSizeInfo2 = adSizeInfo3;
                        bool2 = bool4;
                        Object decodeNullableSerializableElement26 = beginStructure.decodeNullableSerializableElement(descriptor2, 11, v0.f69529a, num5);
                        i11 |= 2048;
                        Unit unit13 = Unit.f60915a;
                        obj9 = obj13;
                        num5 = decodeNullableSerializableElement26;
                        map3 = map5;
                        list5 = list7;
                        str23 = str19;
                        list8 = list3;
                        Object obj2122222222222 = obj11;
                        bool3 = bool2;
                        templateSettings3 = templateSettings2;
                        str28 = obj2122222222222;
                        break;
                    case 12:
                        webViewSettings2 = webViewSettings3;
                        str19 = str23;
                        str13 = str25;
                        str14 = str26;
                        list3 = list8;
                        list7 = list9;
                        viewAbility2 = viewAbility3;
                        str15 = str27;
                        obj11 = str28;
                        templateSettings2 = templateSettings4;
                        str16 = str29;
                        str17 = str30;
                        obj12 = obj19;
                        num4 = num6;
                        adSizeInfo2 = adSizeInfo3;
                        bool2 = bool4;
                        str12 = str24;
                        map3 = beginStructure.decodeNullableSerializableElement(descriptor2, 12, AdPayload.TpatSerializer.INSTANCE, map6);
                        i11 |= 4096;
                        Unit unit14 = Unit.f60915a;
                        obj9 = obj13;
                        list5 = list7;
                        str23 = str19;
                        list8 = list3;
                        Object obj21222222222222 = obj11;
                        bool3 = bool2;
                        templateSettings3 = templateSettings2;
                        str28 = obj21222222222222;
                        break;
                    case 13:
                        webViewSettings2 = webViewSettings3;
                        str19 = str23;
                        str14 = str26;
                        list3 = list8;
                        list7 = list9;
                        viewAbility2 = viewAbility3;
                        str15 = str27;
                        obj11 = str28;
                        templateSettings2 = templateSettings4;
                        str16 = str29;
                        str17 = str30;
                        obj12 = obj19;
                        num4 = num6;
                        adSizeInfo2 = adSizeInfo3;
                        bool2 = bool4;
                        str13 = str25;
                        Object decodeNullableSerializableElement27 = beginStructure.decodeNullableSerializableElement(descriptor2, 13, w2.f69539a, str24);
                        i11 |= 8192;
                        Unit unit15 = Unit.f60915a;
                        obj9 = obj13;
                        str12 = decodeNullableSerializableElement27;
                        map3 = map6;
                        list5 = list7;
                        str23 = str19;
                        list8 = list3;
                        Object obj212222222222222 = obj11;
                        bool3 = bool2;
                        templateSettings3 = templateSettings2;
                        str28 = obj212222222222222;
                        break;
                    case 14:
                        webViewSettings2 = webViewSettings3;
                        str19 = str23;
                        list3 = list8;
                        list7 = list9;
                        viewAbility2 = viewAbility3;
                        str15 = str27;
                        obj11 = str28;
                        templateSettings2 = templateSettings4;
                        str16 = str29;
                        str17 = str30;
                        obj12 = obj19;
                        num4 = num6;
                        adSizeInfo2 = adSizeInfo3;
                        bool2 = bool4;
                        str14 = str26;
                        Object decodeNullableSerializableElement28 = beginStructure.decodeNullableSerializableElement(descriptor2, 14, w2.f69539a, str25);
                        i11 |= 16384;
                        Unit unit16 = Unit.f60915a;
                        obj9 = obj13;
                        str13 = decodeNullableSerializableElement28;
                        map3 = map6;
                        str12 = str24;
                        list5 = list7;
                        str23 = str19;
                        list8 = list3;
                        Object obj2122222222222222 = obj11;
                        bool3 = bool2;
                        templateSettings3 = templateSettings2;
                        str28 = obj2122222222222222;
                        break;
                    case 15:
                        webViewSettings2 = webViewSettings3;
                        str19 = str23;
                        List list10 = list8;
                        list7 = list9;
                        viewAbility2 = viewAbility3;
                        str15 = str27;
                        obj11 = str28;
                        templateSettings2 = templateSettings4;
                        str16 = str29;
                        str17 = str30;
                        obj12 = obj19;
                        num4 = num6;
                        adSizeInfo2 = adSizeInfo3;
                        bool2 = bool4;
                        list3 = list10;
                        Object decodeNullableSerializableElement29 = beginStructure.decodeNullableSerializableElement(descriptor2, 15, w2.f69539a, str26);
                        i11 |= 32768;
                        Unit unit17 = Unit.f60915a;
                        obj9 = obj13;
                        str14 = decodeNullableSerializableElement29;
                        map3 = map6;
                        str12 = str24;
                        str13 = str25;
                        list5 = list7;
                        str23 = str19;
                        list8 = list3;
                        Object obj21222222222222222 = obj11;
                        bool3 = bool2;
                        templateSettings3 = templateSettings2;
                        str28 = obj21222222222222222;
                        break;
                    case 16:
                        webViewSettings2 = webViewSettings3;
                        viewAbility2 = viewAbility3;
                        str15 = str27;
                        obj11 = str28;
                        templateSettings2 = templateSettings4;
                        str16 = str29;
                        str17 = str30;
                        obj12 = obj19;
                        num4 = num6;
                        adSizeInfo2 = adSizeInfo3;
                        bool2 = bool4;
                        Object decodeNullableSerializableElement30 = beginStructure.decodeNullableSerializableElement(descriptor2, 16, new f(w2.f69539a), list8);
                        i11 |= 65536;
                        Unit unit18 = Unit.f60915a;
                        obj9 = obj13;
                        str12 = str24;
                        str13 = str25;
                        str14 = str26;
                        list5 = list9;
                        str23 = str23;
                        list8 = decodeNullableSerializableElement30;
                        map3 = map6;
                        Object obj212222222222222222 = obj11;
                        bool3 = bool2;
                        templateSettings3 = templateSettings2;
                        str28 = obj212222222222222222;
                        break;
                    case 17:
                        webViewSettings2 = webViewSettings3;
                        str20 = str23;
                        str15 = str27;
                        obj11 = str28;
                        templateSettings2 = templateSettings4;
                        str16 = str29;
                        str17 = str30;
                        obj12 = obj19;
                        num4 = num6;
                        adSizeInfo2 = adSizeInfo3;
                        bool2 = bool4;
                        viewAbility2 = viewAbility3;
                        Object decodeNullableSerializableElement31 = beginStructure.decodeNullableSerializableElement(descriptor2, 17, new f(w2.f69539a), list9);
                        i11 |= 131072;
                        Unit unit19 = Unit.f60915a;
                        obj9 = obj13;
                        list5 = decodeNullableSerializableElement31;
                        map3 = map6;
                        str12 = str24;
                        str13 = str25;
                        str14 = str26;
                        str23 = str20;
                        Object obj2122222222222222222 = obj11;
                        bool3 = bool2;
                        templateSettings3 = templateSettings2;
                        str28 = obj2122222222222222222;
                        break;
                    case 18:
                        webViewSettings2 = webViewSettings3;
                        str20 = str23;
                        obj11 = str28;
                        templateSettings2 = templateSettings4;
                        str16 = str29;
                        str17 = str30;
                        obj12 = obj19;
                        num4 = num6;
                        adSizeInfo2 = adSizeInfo3;
                        bool2 = bool4;
                        str15 = str27;
                        Object decodeNullableSerializableElement32 = beginStructure.decodeNullableSerializableElement(descriptor2, 18, AdPayload$ViewAbility$$serializer.INSTANCE, viewAbility3);
                        i11 |= 262144;
                        Unit unit20 = Unit.f60915a;
                        obj9 = obj13;
                        viewAbility2 = decodeNullableSerializableElement32;
                        map3 = map6;
                        str12 = str24;
                        str13 = str25;
                        str14 = str26;
                        list5 = list9;
                        str23 = str20;
                        Object obj21222222222222222222 = obj11;
                        bool3 = bool2;
                        templateSettings3 = templateSettings2;
                        str28 = obj21222222222222222222;
                        break;
                    case 19:
                        webViewSettings2 = webViewSettings3;
                        str20 = str23;
                        Object obj23 = str28;
                        templateSettings2 = templateSettings4;
                        str16 = str29;
                        str17 = str30;
                        obj12 = obj19;
                        num4 = num6;
                        adSizeInfo2 = adSizeInfo3;
                        bool2 = bool4;
                        obj11 = obj23;
                        Object decodeNullableSerializableElement33 = beginStructure.decodeNullableSerializableElement(descriptor2, 19, w2.f69539a, str27);
                        i11 |= 524288;
                        Unit unit21 = Unit.f60915a;
                        obj9 = obj13;
                        str15 = decodeNullableSerializableElement33;
                        map3 = map6;
                        str12 = str24;
                        str13 = str25;
                        str14 = str26;
                        list5 = list9;
                        viewAbility2 = viewAbility3;
                        str23 = str20;
                        Object obj212222222222222222222 = obj11;
                        bool3 = bool2;
                        templateSettings3 = templateSettings2;
                        str28 = obj212222222222222222222;
                        break;
                    case 20:
                        webViewSettings2 = webViewSettings3;
                        String str33 = str23;
                        str16 = str29;
                        str17 = str30;
                        obj12 = obj19;
                        num4 = num6;
                        adSizeInfo2 = adSizeInfo3;
                        Object decodeNullableSerializableElement34 = beginStructure.decodeNullableSerializableElement(descriptor2, 20, w2.f69539a, str28);
                        i11 |= 1048576;
                        Unit unit22 = Unit.f60915a;
                        obj9 = obj13;
                        bool3 = bool4;
                        str12 = str24;
                        str13 = str25;
                        str14 = str26;
                        list5 = list9;
                        viewAbility2 = viewAbility3;
                        str15 = str27;
                        templateSettings3 = templateSettings4;
                        str23 = str33;
                        str28 = decodeNullableSerializableElement34;
                        map3 = map6;
                        break;
                    case 21:
                        webViewSettings2 = webViewSettings3;
                        String str34 = str23;
                        str17 = str30;
                        obj12 = obj19;
                        num4 = num6;
                        adSizeInfo2 = adSizeInfo3;
                        str16 = str29;
                        Object decodeNullableSerializableElement35 = beginStructure.decodeNullableSerializableElement(descriptor2, 21, AdPayload$TemplateSettings$$serializer.INSTANCE, templateSettings4);
                        i11 |= 2097152;
                        Unit unit23 = Unit.f60915a;
                        obj9 = obj13;
                        bool3 = bool4;
                        str12 = str24;
                        str13 = str25;
                        str14 = str26;
                        list5 = list9;
                        viewAbility2 = viewAbility3;
                        str15 = str27;
                        str23 = str34;
                        templateSettings3 = decodeNullableSerializableElement35;
                        map3 = map6;
                        break;
                    case 22:
                        webViewSettings2 = webViewSettings3;
                        str21 = str23;
                        obj12 = obj19;
                        num4 = num6;
                        adSizeInfo2 = adSizeInfo3;
                        str17 = str30;
                        Object decodeNullableSerializableElement36 = beginStructure.decodeNullableSerializableElement(descriptor2, 22, w2.f69539a, str29);
                        i11 |= 4194304;
                        Unit unit24 = Unit.f60915a;
                        obj9 = obj13;
                        str16 = decodeNullableSerializableElement36;
                        bool3 = bool4;
                        map3 = map6;
                        str12 = str24;
                        str13 = str25;
                        str14 = str26;
                        list5 = list9;
                        viewAbility2 = viewAbility3;
                        str15 = str27;
                        templateSettings3 = templateSettings4;
                        str23 = str21;
                        break;
                    case 23:
                        webViewSettings2 = webViewSettings3;
                        str21 = str23;
                        num4 = num6;
                        adSizeInfo2 = adSizeInfo3;
                        obj12 = obj19;
                        Object decodeNullableSerializableElement37 = beginStructure.decodeNullableSerializableElement(descriptor2, 23, w2.f69539a, str30);
                        i11 |= 8388608;
                        Unit unit25 = Unit.f60915a;
                        obj9 = obj13;
                        str17 = decodeNullableSerializableElement37;
                        bool3 = bool4;
                        map3 = map6;
                        str12 = str24;
                        str13 = str25;
                        str14 = str26;
                        list5 = list9;
                        viewAbility2 = viewAbility3;
                        str15 = str27;
                        templateSettings3 = templateSettings4;
                        str16 = str29;
                        str23 = str21;
                        break;
                    case 24:
                        webViewSettings2 = webViewSettings3;
                        str21 = str23;
                        adSizeInfo2 = adSizeInfo3;
                        num4 = num6;
                        Object decodeNullableSerializableElement38 = beginStructure.decodeNullableSerializableElement(descriptor2, 24, v0.f69529a, obj19);
                        i11 |= 16777216;
                        Unit unit26 = Unit.f60915a;
                        obj9 = obj13;
                        obj12 = decodeNullableSerializableElement38;
                        bool3 = bool4;
                        map3 = map6;
                        str12 = str24;
                        str13 = str25;
                        str14 = str26;
                        list5 = list9;
                        viewAbility2 = viewAbility3;
                        str15 = str27;
                        templateSettings3 = templateSettings4;
                        str16 = str29;
                        str17 = str30;
                        str23 = str21;
                        break;
                    case 25:
                        webViewSettings2 = webViewSettings3;
                        str21 = str23;
                        adSizeInfo2 = adSizeInfo3;
                        Object decodeNullableSerializableElement39 = beginStructure.decodeNullableSerializableElement(descriptor2, 25, v0.f69529a, num6);
                        i11 |= 33554432;
                        Unit unit27 = Unit.f60915a;
                        obj9 = obj13;
                        num4 = decodeNullableSerializableElement39;
                        bool3 = bool4;
                        map3 = map6;
                        str12 = str24;
                        str13 = str25;
                        str14 = str26;
                        list5 = list9;
                        viewAbility2 = viewAbility3;
                        str15 = str27;
                        templateSettings3 = templateSettings4;
                        str16 = str29;
                        str17 = str30;
                        obj12 = obj19;
                        str23 = str21;
                        break;
                    case 26:
                        webViewSettings2 = webViewSettings3;
                        str21 = str23;
                        Object decodeNullableSerializableElement40 = beginStructure.decodeNullableSerializableElement(descriptor2, 26, AdPayload$AdSizeInfo$$serializer.INSTANCE, adSizeInfo3);
                        i11 |= 67108864;
                        Unit unit28 = Unit.f60915a;
                        obj9 = obj13;
                        adSizeInfo2 = decodeNullableSerializableElement40;
                        bool3 = bool4;
                        map3 = map6;
                        str12 = str24;
                        str13 = str25;
                        str14 = str26;
                        list5 = list9;
                        viewAbility2 = viewAbility3;
                        str15 = str27;
                        templateSettings3 = templateSettings4;
                        str16 = str29;
                        str17 = str30;
                        obj12 = obj19;
                        num4 = num6;
                        str23 = str21;
                        break;
                    case 27:
                        str21 = str23;
                        webViewSettings2 = webViewSettings3;
                        Object decodeNullableSerializableElement41 = beginStructure.decodeNullableSerializableElement(descriptor2, 27, i.f69441a, bool4);
                        i11 |= 134217728;
                        Unit unit29 = Unit.f60915a;
                        obj9 = obj13;
                        bool3 = decodeNullableSerializableElement41;
                        map3 = map6;
                        str12 = str24;
                        str13 = str25;
                        str14 = str26;
                        list5 = list9;
                        viewAbility2 = viewAbility3;
                        str15 = str27;
                        templateSettings3 = templateSettings4;
                        str16 = str29;
                        str17 = str30;
                        obj12 = obj19;
                        num4 = num6;
                        adSizeInfo2 = adSizeInfo3;
                        str23 = str21;
                        break;
                    case 28:
                        str21 = str23;
                        Object decodeNullableSerializableElement42 = beginStructure.decodeNullableSerializableElement(descriptor2, 28, AdPayload$WebViewSettings$$serializer.INSTANCE, webViewSettings3);
                        i11 |= 268435456;
                        Unit unit30 = Unit.f60915a;
                        obj9 = obj13;
                        webViewSettings2 = decodeNullableSerializableElement42;
                        map3 = map6;
                        str12 = str24;
                        str13 = str25;
                        str14 = str26;
                        list5 = list9;
                        viewAbility2 = viewAbility3;
                        str15 = str27;
                        templateSettings3 = templateSettings4;
                        str16 = str29;
                        str17 = str30;
                        obj12 = obj19;
                        num4 = num6;
                        adSizeInfo2 = adSizeInfo3;
                        bool3 = bool4;
                        str23 = str21;
                        break;
                    default:
                        throw new UnknownFieldException(decodeElementIndex);
                }
                map6 = map3;
                list9 = list5;
                webViewSettings3 = webViewSettings2;
                templateSettings4 = templateSettings3;
                adSizeInfo3 = adSizeInfo2;
                num6 = num4;
                obj19 = obj12;
                str30 = str17;
                str29 = str16;
                bool4 = bool3;
                str27 = str15;
                viewAbility3 = viewAbility2;
                str26 = str14;
                str25 = str13;
                str24 = str12;
                obj13 = obj9;
            }
            Object obj24 = obj13;
            Object obj25 = obj20;
            AdPayload.WebViewSettings webViewSettings4 = webViewSettings3;
            str = str24;
            List list11 = list8;
            list = list9;
            str2 = str27;
            String str35 = str28;
            templateSettings = templateSettings4;
            String str36 = str29;
            bool = bool4;
            i10 = i11;
            str3 = str31;
            num2 = num5;
            obj = obj14;
            str4 = str22;
            obj2 = obj15;
            obj3 = obj16;
            obj4 = obj17;
            obj5 = obj18;
            str5 = str23;
            webViewSettings = webViewSettings4;
            adSizeInfo = adSizeInfo3;
            num3 = num6;
            str6 = str30;
            str7 = str36;
            str8 = str35;
            viewAbility = viewAbility3;
            list2 = list11;
            str9 = str26;
            str10 = str25;
            obj6 = obj25;
            obj7 = obj24;
            map = map6;
            obj8 = obj19;
        }
        beginStructure.endStructure(descriptor2);
        return new AdPayload.AdUnit(i10, str3, str5, (String) obj6, (Integer) obj7, (String) obj5, (Boolean) obj3, (Boolean) obj4, (Boolean) obj2, str4, (String) obj, num, num2, map, str, str10, str9, list2, list, viewAbility, str2, str8, templateSettings, str7, str6, (Integer) obj8, num3, adSizeInfo, bool, webViewSettings, (r2) null);
    }

    @Override // kotlinx.serialization.KSerializer, st.l, st.c
    @NotNull
    public SerialDescriptor getDescriptor() {
        return descriptor;
    }

    @Override // st.l
    public void serialize(@NotNull Encoder encoder, @NotNull AdPayload.AdUnit value) {
        Intrinsics.checkNotNullParameter(encoder, "encoder");
        Intrinsics.checkNotNullParameter(value, "value");
        SerialDescriptor descriptor2 = getDescriptor();
        d beginStructure = encoder.beginStructure(descriptor2);
        AdPayload.AdUnit.write$Self(value, beginStructure, descriptor2);
        beginStructure.endStructure(descriptor2);
    }

    @Override // vt.m0
    @NotNull
    public KSerializer<?>[] typeParametersSerializers() {
        return m0.a.a(this);
    }
}
